// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8R4Pf8PyONOdoNWHgoSxHWLXjJ_tZnxg',
    appId: '1:758168625539:web:ea9303cd359d15829c56b6',
    messagingSenderId: '758168625539',
    projectId: 'ditonton-da7a3',
    authDomain: 'ditonton-da7a3.firebaseapp.com',
    storageBucket: 'ditonton-da7a3.appspot.com',
    measurementId: 'G-92J1RX2MBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKsQM1LBXfTnBj7uvVFPPmuo51VzUhSyI',
    appId: '1:758168625539:android:abcb3c66b2d618979c56b6',
    messagingSenderId: '758168625539',
    projectId: 'ditonton-da7a3',
    storageBucket: 'ditonton-da7a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3lW2DL89F5613TdqfsIg3kYN48e2ghrI',
    appId: '1:758168625539:ios:aff565f1984579739c56b6',
    messagingSenderId: '758168625539',
    projectId: 'ditonton-da7a3',
    storageBucket: 'ditonton-da7a3.appspot.com',
    iosBundleId: 'com.dicoding.ditonton.ditonton',
  );
}
